Para A = V, B = V e C = F
a) (A e B) ou (A xou B)

(Verdadeiro e Verdadeiro) ou (Verdadeiro xou Verdadeiro)
(Verdadeiro) ou (falso)
Verdadeiro


Para A = V, B = V e C = F
b) (A ou B) e (A e C) 
(Verdadeiro ou Verdadeiro) e (Verdadeiro e Falso)
(Verdadeiro) e (Falso)
Falso


Para A = V, B = V e C = F
c) A ou C e B xou A e não B
Verdadeiro ou Falso e Verdadeiro xou Verdadeiro e Falso
Verdadeiro e Falso
Falso


